INSERT INTO DEPARTMENT VALUES (1, 'Register');
INSERT INTO DEPARTMENT VALUES (2, 'Finance');
INSERT INTO DEPARTMENT VALUES (3, 'Library');

INSERT INTO POSITION (PNUMBER, PNAME, ACCESSNO) VALUES (1, 'Admin', '111111');
INSERT INTO POSITION (PNUMBER, PNAME, ACCESSNO) VALUES (2, 'Employee', '110000');

INSERT INTO ROOM_STATUS (SNUMBER, SNAME) VALUES (1, 'Available');
INSERT INTO ROOM_STATUS (SNUMBER, SNAME) VALUES (2, 'Not Available');

INSERT INTO EMPLOYEE_STATUS (SNUMBER, SNAME) VALUES (1, 'Active');
INSERT INTO EMPLOYEE_STATUS (SNUMBER, SNAME) VALUES (2, 'Inactive');

INSERT INTO BOOKING_STATUS VALUES (1, 'Approved');
INSERT INTO BOOKING_STATUS VALUES (2, 'Verifying');
INSERT INTO BOOKING_STATUS VALUES (3, 'Not Approved');
INSERT INTO BOOKING_STATUS VALUES (4, 'Canceled');
INSERT INTO BOOKING_STATUS VALUES (5, 'Complete');
INSERT INTO BOOKING_STATUS VALUES (6, 'Late');

INSERT INTO BUILDING VALUES (1, 'D');
INSERT INTO BUILDING VALUES (2, 'F');
INSERT INTO BUILDING VALUES (3, 'MII');

INSERT INTO FLOOR (FLNUMBER, FLNAME, BNO) VALUES (1, '1', 1);
INSERT INTO FLOOR (FLNUMBER, FLNAME, BNO) VALUES (2, '2', 1);

INSERT INTO ROOM (RNUMBER, RNAME, CAPACITY, VIP, FLNO) VALUES (1, '102', 40, 0, 1);
INSERT INTO ROOM (RNUMBER, RNAME, CAPACITY, VIP, FLNO) VALUES (2, '103', 40, 0, 1);
INSERT INTO ROOM (RNUMBER, RNAME, CAPACITY, VIP, FLNO) VALUES (3, '202', 10, 1, 2);

INSERT INTO EMPLOYEE (ENUMBER, FNAME, LNAME, SCORE, EMAIL, USERNAME, PASSWORD, DNO, PNO, SNO) VALUES (1, 'A', 'A', 0, 'Aa@gmail.com', 'Admin', '1234', 1, 1, 1);
INSERT INTO EMPLOYEE (ENUMBER, FNAME, LNAME, SCORE, EMAIL, USERNAME, PASSWORD, DNO, PNO, SNO) VALUES (2, 'B', 'B', 0, 'Baka@gmail.com', 'Boom', '4321', 1, 2, 1);

INSERT INTO BOOKING VALUES (1, TO_DATE('2024-10-10', 'YYYY-MM-DD'), 2);

INSERT INTO BOOKING_LIST VALUES (1, 1, 1, TO_DATE('2024-10-10', 'YYYY-MM-DD'), '09:00', '12:00', '00100001', 1);
INSERT INTO BOOKING_LIST VALUES (2, 1, 3, TO_DATE('2024-10-11', 'YYYY-MM-DD'), '09:00', '12:00', '00200001', 2);
