DROP TABLE ACCESS_LIST CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE BOOKING_LIST CASCADE CONSTRAINTS;
DROP TABLE BOOKING_STATUS CASCADE CONSTRAINTS;
DROP TABLE BUILDING CASCADE CONSTRAINTS;
DROP TABLE CANCEL_BOOKING CASCADE CONSTRAINTS;
DROP TABLE DENY_BOOKING CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_STATUS CASCADE CONSTRAINTS;
DROP TABLE FLOOR CASCADE CONSTRAINTS;
DROP TABLE LOCK_LIST CASCADE CONSTRAINTS;
DROP TABLE POSITION CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP TABLE ROOM_STATUS CASCADE CONSTRAINTS;
DROP TABLE UNLOCK_LIST CASCADE CONSTRAINTS;

CREATE TABLE department (
   DNumber  NUMBER(3),
   DName  VARCHAR2(15),
   CONSTRAINT pk_department PRIMARY KEY (DNumber)
);

CREATE TABLE position (
   PNumber  NUMBER(3),
   PName  VARCHAR2(15),
   AccessNo  VARCHAR2(15),
   CONSTRAINT pk_position PRIMARY KEY (PNumber)
);

CREATE TABLE room_status (
   SNumber  NUMBER(3),
   SName  VARCHAR2(15),
   CONSTRAINT pk_room_status PRIMARY KEY (SNumber)
);

CREATE TABLE employee_status (
   SNumber  NUMBER(3),
   SName  VARCHAR2(15),
   CONSTRAINT pk_employee_status PRIMARY KEY (SNumber)
);

CREATE TABLE booking_status (
   SNumber  NUMBER(3),
   SName  VARCHAR2(15),
   CONSTRAINT pk_booking_status PRIMARY KEY (SNumber)
);

CREATE TABLE building (
   BNumber  NUMBER(3),
   BName  VARCHAR2(15),
   CONSTRAINT pk_building PRIMARY KEY (BNumber)
);

CREATE TABLE floor (
   FlNumber  NUMBER(3),
   FlName  VARCHAR2(3),
   BNo  NUMBER(3),
   CONSTRAINT pk_floor PRIMARY KEY (FlNumber)
);

CREATE TABLE room (
   RNumber  NUMBER(3),
   RName  VARCHAR2(15),
   Capacity NUMBER(3),
   VIP  NUMBER(1),
   FlNo NUMBER(3),
   CONSTRAINT pk_room PRIMARY KEY (RNumber)
);

CREATE TABLE employee (
   ENumber  NUMBER(3),
   FName  VARCHAR2(15),
   LName  VARCHAR2(15),
   score  NUMBER(1),
   Email  VARCHAR2(30),
   username  VARCHAR2(15),
   password  VARCHAR2(15),
   DNo  NUMBER(3),
   PNo  NUMBER(3),
   SNo  NUMBER(3),
   CONSTRAINT pk_employee PRIMARY KEY (ENumber)
);

CREATE TABLE booking (
   BKNumber  NUMBER(5),
   BKDate   DATE,
   ENo NUMBER(3),
   CONSTRAINT pk_booking PRIMARY KEY (BKNumber)
);

CREATE TABLE booking_list (
   BKLNumber  NUMBER(3),
   BKLNo   NUMBER(5),
   RNo  NUMBER(3),
   Start_Date   DATE,
   Start_Time   VARCHAR2(5),
   End_Time     VARCHAR2(5),
   details  VARCHAR2(30),
   QR       VARCHAR2(8),
   SNo      NUMBER(3),
   CONSTRAINT pk_booking_list PRIMARY KEY (BKLNumber)
);

CREATE TABLE access_list (
   ACNumber  NUMBER(3),
   BKLNo   NUMBER(3),
   BKNo  NUMBER(3),
   Access_Time   VARCHAR2(5),
   CONSTRAINT pk_access_list PRIMARY KEY (ACNumber)
);

CREATE TABLE deny_booking (
   DNNumber  NUMBER(3),
   BKLNo   NUMBER(3),
   BKNo  NUMBER(3),
   details   VARCHAR2(30),
   CONSTRAINT pk_deny_booking PRIMARY KEY (DNNumber)
);

CREATE TABLE cancel_booking (
   CCNumber  NUMBER(3),
   BKLNo   NUMBER(3),
   BKNo  NUMBER(3),
   details   VARCHAR2(30),
   CONSTRAINT pk_cancel_booking PRIMARY KEY (CCNumber)
);

CREATE TABLE lock_list (
   LKNo  NUMBER(3),
   ENo   NUMBER(3),
   LKDate  DATE,
   CONSTRAINT pk_lock_list PRIMARY KEY (LKNo)
);

CREATE TABLE unlock_list (
   ULKNo  NUMBER(3),
   ENo   NUMBER(3),
   LKDate  DATE,
   CONSTRAINT pk_unlock_list PRIMARY KEY (ULKNo)
);

ALTER TABLE FLOOR
  ADD CONSTRAINT FK_FL_BD FOREIGN KEY (BNo)
  REFERENCES BUILDING (BNumber);

ALTER TABLE ROOM
  ADD CONSTRAINT FK_RM_FL FOREIGN KEY (FlNo)
  REFERENCES FLOOR (FlNumber);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT FK_EMP_DP FOREIGN KEY (DNo)
  REFERENCES DEPARTMENT (DNumber);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT FK_EMP_PO FOREIGN KEY (PNo)
  REFERENCES POSITION (PNumber);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT FK_EMP_ST FOREIGN KEY (SNo)
  REFERENCES EMPLOYEE_STATUS (SNumber);

ALTER TABLE BOOKING
  ADD CONSTRAINT FK_BK_EM FOREIGN KEY (ENo)
  REFERENCES EMPLOYEE (ENumber);

ALTER TABLE BOOKING_LIST
  ADD CONSTRAINT FK_BKL_BK FOREIGN KEY (BKLNo)
  REFERENCES BOOKING (BKNumber);

ALTER TABLE BOOKING_LIST
  ADD CONSTRAINT FK_BKL_RM FOREIGN KEY (RNo)
  REFERENCES ROOM (RNumber);

ALTER TABLE BOOKING_LIST
  ADD CONSTRAINT FK_BKL_ST FOREIGN KEY (SNo)
  REFERENCES BOOKING_STATUS (SNumber);

ALTER TABLE ACCESS_LIST
  ADD CONSTRAINT FK_AC_BKL FOREIGN KEY (BKLNo)
  REFERENCES BOOKING_LIST (BKLNumber);

ALTER TABLE ACCESS_LIST
  ADD CONSTRAINT FK_AC_BK FOREIGN KEY (BKNo)
  REFERENCES BOOKING (BKNumber);

ALTER TABLE DENY_BOOKING
  ADD CONSTRAINT FK_DN_BKL FOREIGN KEY (BKLNo)
  REFERENCES BOOKING_LIST (BKLNumber);

ALTER TABLE DENY_BOOKING
  ADD CONSTRAINT FK_DN_BK FOREIGN KEY (BKNo)
  REFERENCES BOOKING (BKNumber);

ALTER TABLE CANCEL_BOOKING
  ADD CONSTRAINT FK_CC_BKL FOREIGN KEY (BKLNo)
  REFERENCES BOOKING_LIST (BKLNumber);

ALTER TABLE CANCEL_BOOKING
  ADD CONSTRAINT FK_CC_BK FOREIGN KEY (BKNo)
  REFERENCES BOOKING (BKNumber);

ALTER TABLE LOCK_LIST
  ADD CONSTRAINT FK_LK_EMP FOREIGN KEY (ENo)
  REFERENCES EMPLOYEE (ENumber);

ALTER TABLE UNLOCK_LIST
  ADD CONSTRAINT FK_ULK_EMP FOREIGN KEY (ENo)
  REFERENCES EMPLOYEE (ENumber);
