/*
  Warnings:

  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
PRAGMA foreign_keys=off;
DROP TABLE "User";
PRAGMA foreign_keys=on;

-- CreateTable
CREATE TABLE "Department" (
    "DNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Position" (
    "PNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PName" TEXT NOT NULL,
    "AccessNo" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "RoomStatus" (
    "SNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "EmployeeStatus" (
    "SNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "BookingStatus" (
    "SNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "SName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Building" (
    "BNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Floor" (
    "FlNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "FlName" TEXT NOT NULL,
    "BNo" INTEGER NOT NULL,
    CONSTRAINT "Floor_BNo_fkey" FOREIGN KEY ("BNo") REFERENCES "Building" ("BNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Room" (
    "RNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "RName" TEXT NOT NULL,
    "Capacity" INTEGER NOT NULL,
    "VIP" INTEGER NOT NULL,
    "FlNo" INTEGER NOT NULL,
    "SNo" INTEGER NOT NULL,
    CONSTRAINT "Room_SNo_fkey" FOREIGN KEY ("SNo") REFERENCES "RoomStatus" ("SNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Room_FlNo_fkey" FOREIGN KEY ("FlNo") REFERENCES "Floor" ("FlNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Employee" (
    "ENumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "FName" TEXT NOT NULL,
    "LName" TEXT NOT NULL,
    "score" INTEGER NOT NULL,
    "Email" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "DNo" INTEGER NOT NULL,
    "PNo" INTEGER NOT NULL,
    "SNo" INTEGER NOT NULL,
    CONSTRAINT "Employee_DNo_fkey" FOREIGN KEY ("DNo") REFERENCES "Department" ("DNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Employee_PNo_fkey" FOREIGN KEY ("PNo") REFERENCES "Position" ("PNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Employee_SNo_fkey" FOREIGN KEY ("SNo") REFERENCES "EmployeeStatus" ("SNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Booking" (
    "BKNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BKDate" DATETIME NOT NULL,
    "ENo" INTEGER NOT NULL,
    CONSTRAINT "Booking_ENo_fkey" FOREIGN KEY ("ENo") REFERENCES "Employee" ("ENumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "BookingList" (
    "BKLNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BKLNo" INTEGER NOT NULL,
    "RNo" INTEGER NOT NULL,
    "Start_Date" DATETIME NOT NULL,
    "Start_Time" TEXT NOT NULL,
    "End_Time" TEXT NOT NULL,
    "details" TEXT NOT NULL,
    "QR" TEXT NOT NULL,
    "SNo" INTEGER NOT NULL,
    CONSTRAINT "BookingList_BKLNo_fkey" FOREIGN KEY ("BKLNo") REFERENCES "Booking" ("BKNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BookingList_RNo_fkey" FOREIGN KEY ("RNo") REFERENCES "Room" ("RNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "BookingList_SNo_fkey" FOREIGN KEY ("SNo") REFERENCES "BookingStatus" ("SNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AccessList" (
    "ACNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BKLNo" INTEGER NOT NULL,
    "BKNo" INTEGER NOT NULL,
    "AccessTime" TEXT NOT NULL,
    CONSTRAINT "AccessList_BKLNo_fkey" FOREIGN KEY ("BKLNo") REFERENCES "BookingList" ("BKLNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "AccessList_BKNo_fkey" FOREIGN KEY ("BKNo") REFERENCES "Booking" ("BKNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "DenyBooking" (
    "DNNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BKLNo" INTEGER NOT NULL,
    "BKNo" INTEGER NOT NULL,
    "details" TEXT NOT NULL,
    CONSTRAINT "DenyBooking_BKLNo_fkey" FOREIGN KEY ("BKLNo") REFERENCES "BookingList" ("BKLNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "DenyBooking_BKNo_fkey" FOREIGN KEY ("BKNo") REFERENCES "Booking" ("BKNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CancelBooking" (
    "CCNumber" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "BKLNo" INTEGER NOT NULL,
    "BKNo" INTEGER NOT NULL,
    "details" TEXT NOT NULL,
    CONSTRAINT "CancelBooking_BKLNo_fkey" FOREIGN KEY ("BKLNo") REFERENCES "BookingList" ("BKLNumber") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "CancelBooking_BKNo_fkey" FOREIGN KEY ("BKNo") REFERENCES "Booking" ("BKNumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LockList" (
    "LKNo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ENo" INTEGER NOT NULL,
    "LKDate" DATETIME NOT NULL,
    CONSTRAINT "LockList_ENo_fkey" FOREIGN KEY ("ENo") REFERENCES "Employee" ("ENumber") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "UnlockList" (
    "ULKNo" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ENo" INTEGER NOT NULL,
    "LKDate" DATETIME NOT NULL,
    CONSTRAINT "UnlockList_ENo_fkey" FOREIGN KEY ("ENo") REFERENCES "Employee" ("ENumber") ON DELETE RESTRICT ON UPDATE CASCADE
);
